# Page settings

baseurl = "https://nmenetrier.github.io/"
languageCode = "en-us"
defaultContentLanguage = "fr"
title = "CV Nicolas MENETRIER"
theme = "hugo-orbit-theme"
googleAnalytics = "UA-XXXXXXX-Y"

# Do not build files for websites. Need them? Set to false
disableRSS = true
disableSitemap = true
disable404 = true

[params]

# Meta
    description = "Hugo Responsive Resume/CV Theme for Developers"
    author = "Pavel Kanyshev"

# Theme styles

    # The original template comes with 6 colour schemes. You may choose styles below.
    # "styles.css", "styles-2.css", "styles-3.css", "styles-4.css", "styles-5.css", "styles-6.css"
    # are available. Also the source LESS files are included so
    # it’s quick and easy to change the styling and colour scheme.

    styles = "styles-6.css"

# Sidebar sections

    # Profile section
    [params.profile]
        name = "Nicolas Ménétrier"
        tagline = "DevOps"
        avatar = "rayman.png"

    # Contact section
    [params.contact]
        enable = true

        [[params.contact.list]]
        class = "home"
        icon = "fa-home"
        url = "https://www.openstreetmap.org/?mlat=44.7276&mlon=5.0215#map=15/44.7276/5.0215"
        title = "Crest, Drôme, France"

        [[params.contact.list]]
        class = "email"
        icon = "fa-envelope"
        url = "mailto: nmenetrier@protonmail.com"
        title = "nmenetrier@protonmail.com"

        [[params.contact.list]]
        class = "phone"
        icon = "fa-phone"
        url = "tel:+33 7 61 31 82 98"
        title = "+33 7 61 31 82 98"

        [[params.contact.list]]
        class = "website"
        icon = "fa-globe"
        url = "//nmenetrier.github.io"
        title = "nmenetrier.github.io"

        [[params.contact.list]]
        class = "linkedin"
        icon = "fa-linkedin"
        url = "//linkedin.com/in/nmenetrier"
        title = "linkedin.com/in/nmenetrier"

        [[params.contact.list]]
        class = "github"
        icon = "fa-github"
        url = "//github.com/nmenetrier"
        title = "github.com/nmenetrier"

        # [[params.contact.list]]
        # class = "twitter"
        # icon = "fa-twitter"
        # url = "//twitter.com/NicoMenetrier"
        # title = "@NicoMenetrier"

    # Education section
    [params.education]
        enable = true
        title = "Education"

        [[params.education.list]]
        degree = "Licence électronique, signal, image"
        college = "Université de Dijon"
        dates = "2009 - 2010"

        [[params.education.list]]
        degree = "IUT informatique, développement logiciel"
        college = "Université de Dijon"
        dates = "2007 - 2009"

    # Languages section
    [params.language]
        enable = true
        title = "Languages"

        [[params.language.list]]
        language = "Français"
        level = "Langue maternelle"

        [[params.language.list]]
        language = "Anglais"
        level = "Compétence professionelle"

    # Interests section
    [params.interests]
        enable = true
        title = "Interests"

        [[params.interests.list]]
        interest = "Athlétisme"

        [[params.interests.list]]
        interest = "Escalade"

        [[params.interests.list]]
        interest = "Jeu vidéo"

        [[params.interests.list]]
        interest = "Environnement"

# Main body sections

    # You may use markdown in summary, details and intro fields. But don't overdose, it's resume!:)

    # Summary section
    [params.summary]
        enable = true
        icon = "fa-user"
        title = "Career Profile"
        summary = """\
            Curieux, j'aime particulièrement découvrir les arcanes du kernel Linux ainsi qu'automatiser les tâches récurrentes.\n\
            Je souhaiterais m'orienter vers un poste avec plus de développement logiciel, type DevOps ou SRE.\n\
            Plus il y a du temps de dev, plus je suis heureux. :)
            """

    # Experiences section
    [params.experiences]
        enable = true
        icon = "fa-briefcase"
        title = "Experiences"

        [[params.jobs.list]]
        position = "Administrateur Systèmes UNIX"
        dates = "Octobre 2019 - Maintenant"
        company = "Thales, Valence"
        details = """\
            - Traitement d'incidents N2 / N3 sur des infras UNIX / Linux physiques et virtualisées.\n\
            - MCO sur le parc UNIX / Linux.
            """
        badges = ['RHEL', 'Ubuntu', 'Bash', 'Python', 'Ansible', 'Puppet', 'Foreman', 'Git', 'VMWare', 'KVM', 'Openstack']

        [[params.jobs.list]]
        position = "DevOps"
        dates = "Septembre 2016 - Septembre 2019"
        company = "Thales, Paris"
        details = """\
            - Programme VITAM, www.programmevitam.fr.\n\
            - Conception d'une plateforme d'intégration continue.\n\
            - MCO d'une plateforme d'intégration continue.\n\
            - Conception de la solution de packaging et de déploiement du logiciel VITAM.
            """
        badges = ['Centos', 'Debian', 'Bash', 'Java', 'Python', 'Openstack', 'Ansible', 'Jenkins', 'Docker', 'Git', 'Sphinx', 'Consul', 'MongoDB', 'Elasticsearch', 'Agile']

        [[params.jobs.list]]
        position = "DevOps"
        dates = "Août 2015 - Août 2016"
        company = "Axway, Ile de France"
        details = """\
            - Développement de divers outils d'automatisation du RUN.\n\
            - Résolution d'incidents et problèmes N2/N3.\n\
            - TMA sur un outil d'automatisation dedéploiements en prod.\n\
            - Astreintes.
            """
        badges = ['Linux', 'Java', 'PHP', 'Perl', 'Python', 'Ksh', 'J2EE', 'Datapower', 'CFT', 'Apache', 'Docker']

        [[params.jobs.list]]
        position = "Consultant Middleware"
        dates = "Septembre 2011 - Juillet 2015"
        company = "Axway, Ile de France"
        details = """\
            - Traitement d'incidents et changements N2 / N3.\n\
            - Réalisation de changements sur le SI.\n\
            - Astreintes.\n\
            """
        badges = ['Linux', 'Tomcat', 'WAS', 'JBoss', 'IBM Datapower', 'Apache HTTP server']

    # Projects section
    [params.projects]
        enable = false
        icon = "fa-archive"
        title = "Projects"
        intro = "**You can list your side projects or open source libraries in this section.** Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum et ligula in nunc bibendum fringilla a eu lectus"

        [[params.projects.list]]
        title = "Hugrid"
        url = "https://github.com/aerohub/hugrid"
        tagline = "Grid theme for Hugo. It's a kind of boilerplate to perform anyone or anything quickly. Portfolio, collection, bookmarks, contacts and so on"

        [[params.projects.list]]
        title = "Simple FAQ Theme for Hugo"
        url = "https://github.com/aerohub/hugo-faq-theme"
        tagline = "Simple FAQ Theme for Hugo. You may use this theme for building very simple FAQs or note lists."

        [[params.projects.list]]
        title = "Hugo Identity"
        url = "https://github.com/aerohub/hugo-identity-theme"
        tagline = "Little profile/card-style template for Hugo."

        [[params.projects.list]]
        title = "Orbit"
        url = "https://github.com/aerohub/hugo-orbit-theme"
        tagline = "Hugo Resume/CV Theme for Developers."

        [[params.projects.list]]
        title = "Me"
        url = "https://github.com/aerohub/hugo-me-theme"
        tagline = "A simple responsive Hugo theme for personal site."

    # Skills section
    [params.skills]
        enable = true
        icon = "fa-rocket"
        title = "Skills & Proficiency"

        [[params.skills.list]]
        skill = "Linux"
        level = "90%"
                
        [[params.skills.list]]
        skill = "Ansible"
        level = "90%"

        [[params.skills.list]]
        skill = "Bash"
        level = "90%"

        [[params.skills.list]]
        skill = "Docker"
        level = "80%"

        [[params.skills.list]]
        skill = "Jenkins"
        level = "80%"

        [[params.skills.list]]
        skill = "Git"
        level = "75%"

        [[params.skills.list]]
        skill = "Python"
        level = "60%"

        [[params.skills.list]]
        skill = "Godot"
        level = "50%"

    # Footer section

    # The original template is released under the Creative Commons Attribution 3.0 License.
    # Please keep the original attribution link when using for your own project.
    # If you'd like to use the template without the attribution,
    # you can check out other license options via template author's website: themes.3rdwavemedia.com
    # 
    # As for Hugo port you may rewrite the "Ported for..." line with setting your name below.

    [params.footer]
        copyright = ""
